[package]
name = "ctlwatcher"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = { version = "0", features = ["native-tls"]}
futures-util = "0"
serde_json = "1"
clap = { version = "4", features = ["derive"] }
regex = "1"
